<?php
namespace Database\Seeders;

use App\Models\CountryIntake;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountryIntakes extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::transaction(function () {
            DB::table((new CountryIntake())->getTable())->delete();
            DB::table((new CountryIntake())->getTable())->insert( array(
                0 => array(
                    'id' => 1,
                    'country_name' => 'Australia',
                    'country_code' => 'AU',
                    'month_name' => 'February',
                    'created_by' => 'Craydel',
                    'updated_by' => 'Craydel',
                    'deleted_by' => 'Craydel',
                    'created_at' => '2022-05-26 08:00:00',
                    'update_at' => '2022-05-26 08:00:00',
                    'deleted_at' => null
                ), 1 => array(
                    'id' => 2,
                    'country_name' => 'Australia',
                    'country_code' => 'AU',
                    'month_name' => 'July',
                    'created_by' => 'Craydel',
                    'updated_by' => 'Craydel',
                    'deleted_by' => 'Craydel',
                    'created_at' => '2022-05-26 08:00:00',
                    'update_at' => '2022-05-26 08:00:00',
                    'deleted_at' => null
                ), 2 => array(
                    'id' => 3,
                    'country_name' => 'Canada',
                    'country_code' => 'CA',
                    'month_name' => 'January',
                    'created_by' => 'Craydel',
                    'updated_by' => 'Craydel',
                    'deleted_by' => 'Craydel',
                    'created_at' => '2022-05-26 08:00:00',
                    'update_at' => '2022-05-26 08:00:00',
                    'deleted_at' => null
                ), 3 => array(
                    'id' => 4,
                    'country_name' => 'Canada',
                    'country_code' => 'CA',
                    'month_name' => 'May',
                    'created_by' => 'Craydel',
                    'updated_by' => 'Craydel',
                    'deleted_by' => 'Craydel',
                    'created_at' => '2022-05-26 08:00:00',
                    'update_at' => '2022-05-26 08:00:00',
                    'deleted_at' => null
                ), 4 => array(
                    'id' => 5,
                    'country_name' => 'Canada',
                    'country_code' => 'CA',
                    'month_name' => 'September',
                    'created_by' => 'Craydel',
                    'updated_by' => 'Craydel',
                    'deleted_by' => 'Craydel',
                    'created_at' => '2022-05-26 08:00:00',
                    'update_at' => '2022-05-26 08:00:00',
                    'deleted_at' => null
                ), 5 => array(
                    'id' => 6,
                    'country_name' => 'Cyprus',
                    'country_code' => 'CY',
                    'month_name' => 'February',
                    'created_by' => 'Craydel',
                    'updated_by' => 'Craydel',
                    'deleted_by' => 'Craydel',
                    'created_at' => '2022-05-26 08:00:00',
                    'update_at' => '2022-05-26 08:00:00',
                    'deleted_at' => null
                ), 6 => array(
                    'id' => 7,
                    'country_name' => 'Cyprus',
                    'country_code' => 'CY',
                    'month_name' => 'September',
                    'created_by' => 'Craydel',
                    'updated_by' => 'Craydel',
                    'deleted_by' => 'Craydel',
                    'created_at' => '2022-05-26 08:00:00',
                    'update_at' => '2022-05-26 08:00:00',
                    'deleted_at' => null
                ), 7 => array(
                    'id' => 8,
                    'country_name' => 'United Arab Emirates',
                    'country_code' => 'AE',
                    'month_name' => 'January',
                    'created_by' => 'Craydel',
                    'updated_by' => 'Craydel',
                    'deleted_by' => 'Craydel',
                    'created_at' => '2022-05-26 08:00:00',
                    'update_at' => '2022-05-26 08:00:00',
                    'deleted_at' => null
                ), 8 => array(
                    'id' => 9,
                    'country_name' => 'United Arab Emirates',
                    'country_code' => 'AE',
                    'month_name' => 'May',
                    'created_by' => 'Craydel',
                    'updated_by' => 'Craydel',
                    'deleted_by' => 'Craydel',
                    'created_at' => '2022-05-26 08:00:00',
                    'update_at' => '2022-05-26 08:00:00',
                    'deleted_at' => null
                ), 9 => array(
                    'id' => 10,
                    'country_name' => 'United Arab Emirates',
                    'country_code' => 'AE',
                    'month_name' => 'September',
                    'created_by' => 'Craydel',
                    'updated_by' => 'Craydel',
                    'deleted_by' => 'Craydel',
                    'created_at' => '2022-05-26 08:00:00',
                    'update_at' => '2022-05-26 08:00:00',
                    'deleted_at' => null
                ), 10 => array(
                    'id' => 11,
                    'country_name' => 'Germany',
                    'country_code' => 'DE',
                    'month_name' => 'January',
                    'created_by' => 'Craydel',
                    'updated_by' => 'Craydel',
                    'deleted_by' => 'Craydel',
                    'created_at' => '2022-05-26 08:00:00',
                    'update_at' => '2022-05-26 08:00:00',
                    'deleted_at' => null
                ), 11 => array(
                    'id' => 12,
                    'country_name' => 'Germany',
                    'country_code' => 'DE',
                    'month_name' => 'March',
                    'created_by' => 'Craydel',
                    'updated_by' => 'Craydel',
                    'deleted_by' => 'Craydel',
                    'created_at' => '2022-05-26 08:00:00',
                    'update_at' => '2022-05-26 08:00:00',
                    'deleted_at' => null
                ), 12 => array(
                    'id' => 13,
                    'country_name' => 'Germany',
                    'country_code' => 'DE',
                    'month_name' => 'September',
                    'created_by' => 'Craydel',
                    'updated_by' => 'Craydel',
                    'deleted_by' => 'Craydel',
                    'created_at' => '2022-05-26 08:00:00',
                    'update_at' => '2022-05-26 08:00:00',
                    'deleted_at' => null
                ), 13 => array(
                    'id' => 14,
                    'country_name' => 'Germany',
                    'country_code' => 'DE',
                    'month_name' => 'October',
                    'created_by' => 'Craydel',
                    'updated_by' => 'Craydel',
                    'deleted_by' => 'Craydel',
                    'created_at' => '2022-05-26 08:00:00',
                    'update_at' => '2022-05-26 08:00:00',
                    'deleted_at' => null
                ), 14 => array(
                    'id' => 15,
                    'country_name' => 'Ireland',
                    'country_code' => 'IE',
                    'month_name' => 'February',
                    'created_by' => 'Craydel',
                    'updated_by' => 'Craydel',
                    'deleted_by' => 'Craydel',
                    'created_at' => '2022-05-26 08:00:00',
                    'update_at' => '2022-05-26 08:00:00',
                    'deleted_at' => null
                ), 15 => array(
                    'id' => 16,
                    'country_name' => 'Ireland',
                    'country_code' => 'IE',
                    'month_name' => 'September',
                    'created_by' => 'Craydel',
                    'updated_by' => 'Craydel',
                    'deleted_by' => 'Craydel',
                    'created_at' => '2022-05-26 08:00:00',
                    'update_at' => '2022-05-26 08:00:00',
                    'deleted_at' => null
                ), 16 => array(
                    'id' => 17,
                    'country_name' => 'Ireland',
                    'country_code' => 'IE',
                    'month_name' => 'September',
                    'created_by' => 'Craydel',
                    'updated_by' => 'Craydel',
                    'deleted_by' => 'Craydel',
                    'created_at' => '2022-05-26 08:00:00',
                    'update_at' => '2022-05-26 08:00:00',
                    'deleted_at' => null
                ), 17 => array(
                    'id' => 18,
                    'country_name' => 'Kenya',
                    'country_code' => 'KE',
                    'month_name' => 'January',
                    'created_by' => 'Craydel',
                    'updated_by' => 'Craydel',
                    'deleted_by' => 'Craydel',
                    'created_at' => '2022-05-26 08:00:00',
                    'update_at' => '2022-05-26 08:00:00',
                    'deleted_at' => null
                ), 18 => array(
                    'id' => 19,
                    'country_name' => 'Kenya',
                    'country_code' => 'KE',
                    'month_name' => 'May',
                    'created_by' => 'Craydel',
                    'updated_by' => 'Craydel',
                    'deleted_by' => 'Craydel',
                    'created_at' => '2022-05-26 08:00:00',
                    'update_at' => '2022-05-26 08:00:00',
                    'deleted_at' => null
                ), 19 => array(
                    'id' => 20,
                    'country_name' => 'Kenya',
                    'country_code' => 'KE',
                    'month_name' => 'September',
                    'created_by' => 'Craydel',
                    'updated_by' => 'Craydel',
                    'deleted_by' => 'Craydel',
                    'created_at' => '2022-05-26 08:00:00',
                    'update_at' => '2022-05-26 08:00:00',
                    'deleted_at' => null
                ), 20 => array(
                    'id' => 21,
                    'country_name' => 'Spain',
                    'country_code' => 'ES',
                    'month_name' => 'January',
                    'created_by' => 'Craydel',
                    'updated_by' => 'Craydel',
                    'deleted_by' => 'Craydel',
                    'created_at' => '2022-05-26 08:00:00',
                    'update_at' => '2022-05-26 08:00:00',
                    'deleted_at' => null
                ), 21 => array(
                    'id' => 22,
                    'country_name' => 'Spain',
                    'country_code' => 'ES',
                    'month_name' => 'January',
                    'created_by' => 'Craydel',
                    'updated_by' => 'Craydel',
                    'deleted_by' => 'Craydel',
                    'created_at' => '2022-05-26 08:00:00',
                    'update_at' => '2022-05-26 08:00:00',
                    'deleted_at' => null
                ), 22 => array(
                    'id' => 23,
                    'country_name' => 'Spain',
                    'country_code' => 'ES',
                    'month_name' => 'March',
                    'created_by' => 'Craydel',
                    'updated_by' => 'Craydel',
                    'deleted_by' => 'Craydel',
                    'created_at' => '2022-05-26 08:00:00',
                    'update_at' => '2022-05-26 08:00:00',
                    'deleted_at' => null
                ), 23 => array(
                    'id' => 24,
                    'country_name' => 'Spain',
                    'country_code' => 'ES',
                    'month_name' => 'August',
                    'created_by' => 'Craydel',
                    'updated_by' => 'Craydel',
                    'deleted_by' => 'Craydel',
                    'created_at' => '2022-05-26 08:00:00',
                    'update_at' => '2022-05-26 08:00:00',
                    'deleted_at' => null
                ), 24 => array(
                    'id' => 25,
                    'country_name' => 'Spain',
                    'country_code' => 'ES',
                    'month_name' => 'October',
                    'created_by' => 'Craydel',
                    'updated_by' => 'Craydel',
                    'deleted_by' => 'Craydel',
                    'created_at' => '2022-05-26 08:00:00',
                    'update_at' => '2022-05-26 08:00:00',
                    'deleted_at' => null
                ), 25 => array(
                    'id' => 26,
                    'country_name' => 'Switzerland',
                    'country_code' => 'CH',
                    'month_name' => 'January',
                    'created_by' => 'Craydel',
                    'updated_by' => 'Craydel',
                    'deleted_by' => 'Craydel',
                    'created_at' => '2022-05-26 08:00:00',
                    'update_at' => '2022-05-26 08:00:00',
                    'deleted_at' => null
                ), 26 => array(
                    'id' => 27,
                    'country_name' => 'Switzerland',
                    'country_code' => 'CH',
                    'month_name' => 'March',
                    'created_by' => 'Craydel',
                    'updated_by' => 'Craydel',
                    'deleted_by' => 'Craydel',
                    'created_at' => '2022-05-26 08:00:00',
                    'update_at' => '2022-05-26 08:00:00',
                    'deleted_at' => null
                ), 27 => array(
                    'id' => 28,
                    'country_name' => 'Switzerland',
                    'country_code' => 'CH',
                    'month_name' => 'September',
                    'created_by' => 'Craydel',
                    'updated_by' => 'Craydel',
                    'deleted_by' => 'Craydel',
                    'created_at' => '2022-05-26 08:00:00',
                    'update_at' => '2022-05-26 08:00:00',
                    'deleted_at' => null
                ), 28 => array(
                    'id' => 29,
                    'country_name' => 'Switzerland',
                    'country_code' => 'CH',
                    'month_name' => 'October',
                    'created_by' => 'Craydel',
                    'updated_by' => 'Craydel',
                    'deleted_by' => 'Craydel',
                    'created_at' => '2022-05-26 08:00:00',
                    'update_at' => '2022-05-26 08:00:00',
                    'deleted_at' => null
                ), 29 => array(
                    'id' => 30,
                    'country_name' => 'Turkey',
                    'country_code' => 'TR',
                    'month_name' => 'September',
                    'created_by' => 'Craydel',
                    'updated_by' => 'Craydel',
                    'deleted_by' => 'Craydel',
                    'created_at' => '2022-05-26 08:00:00',
                    'update_at' => '2022-05-26 08:00:00',
                    'deleted_at' => null
                ), 30 => array(
                    'id' => 31,
                    'country_name' => 'United Kingdom',
                    'country_code' => 'UK',
                    'month_name' => 'January',
                    'created_by' => 'Craydel',
                    'updated_by' => 'Craydel',
                    'deleted_by' => 'Craydel',
                    'created_at' => '2022-05-26 08:00:00',
                    'update_at' => '2022-05-26 08:00:00',
                    'deleted_at' => null
                ), 31 => array(
                    'id' => 32,
                    'country_name' => 'United Kingdom',
                    'country_code' => 'UK',
                    'month_name' => 'September',
                    'created_by' => 'Craydel',
                    'updated_by' => 'Craydel',
                    'deleted_by' => 'Craydel',
                    'created_at' => '2022-05-26 08:00:00',
                    'update_at' => '2022-05-26 08:00:00',
                    'deleted_at' => null
                ), 32 => array(
                    'id' => 33,
                    'country_name' => 'United States',
                    'country_code' => 'US',
                    'month_name' => 'January',
                    'created_by' => 'Craydel',
                    'updated_by' => 'Craydel',
                    'deleted_by' => 'Craydel',
                    'created_at' => '2022-05-26 08:00:00',
                    'update_at' => '2022-05-26 08:00:00',
                    'deleted_at' => null
                ), 33 => array(
                    'id' => 34,
                    'country_name' => 'United States',
                    'country_code' => 'US',
                    'month_name' => 'August',
                    'created_by' => 'Craydel',
                    'updated_by' => 'Craydel',
                    'deleted_by' => 'Craydel',
                    'created_at' => '2022-05-26 08:00:00',
                    'update_at' => '2022-05-26 08:00:00',
                    'deleted_at' => null
                ), 34 => array(
                    'id' => 35,
                    'country_name' => 'Guyana',
                    'country_code' => 'GY',
                    'month_name' => 'August',
                    'created_by' => 'Craydel',
                    'updated_by' => 'Craydel',
                    'deleted_by' => 'Craydel',
                    'created_at' => '2022-05-26 08:00:00',
                    'update_at' => '2022-05-26 08:00:00',
                    'deleted_at' => null
                ), 35 => array(
                    'id' => 36,
                    'country_name' => 'Malaysia',
                    'country_code' => 'MY',
                    'month_name' => 'January',
                    'created_by' => 'Craydel',
                    'updated_by' => 'Craydel',
                    'deleted_by' => 'Craydel',
                    'created_at' => '2022-05-26 08:00:00',
                    'update_at' => '2022-05-26 08:00:00',
                    'deleted_at' => null
                ), 36 => array(
                    'id' => 37,
                    'country_name' => 'Malaysia',
                    'country_code' => 'MY',
                    'month_name' => 'October',
                    'created_by' => 'Craydel',
                    'updated_by' => 'Craydel',
                    'deleted_by' => 'Craydel',
                    'created_at' => '2022-05-26 08:00:00',
                    'update_at' => '2022-05-26 08:00:00',
                    'deleted_at' => null
                ), 37 => array(
                    'id' => 38,
                    'country_name' => 'Malaysia',
                    'country_code' => 'MY',
                    'month_name' => 'August',
                    'created_by' => 'Craydel',
                    'updated_by' => 'Craydel',
                    'deleted_by' => 'Craydel',
                    'created_at' => '2022-05-26 08:00:00',
                    'update_at' => '2022-05-26 08:00:00',
                    'deleted_at' => null
                ), 38 => array(
                    'id' => 39,
                    'country_name' => 'New Zealand',
                    'country_code' => 'NZ',
                    'month_name' => 'January',
                    'created_by' => 'Craydel',
                    'updated_by' => 'Craydel',
                    'deleted_by' => 'Craydel',
                    'created_at' => '2022-05-26 08:00:00',
                    'update_at' => '2022-05-26 08:00:00',
                    'deleted_at' => null
                ), 39 => array(
                    'id' => 40,
                    'country_name' => 'New Zealand',
                    'country_code' => 'NZ',
                    'month_name' => 'July',
                    'created_by' => 'Craydel',
                    'updated_by' => 'Craydel',
                    'deleted_by' => 'Craydel',
                    'created_at' => '2022-05-26 08:00:00',
                    'update_at' => '2022-05-26 08:00:00',
                    'deleted_at' => null
                ), 40 => array(
                    'id' => 41,
                    'country_name' => 'New Zealand',
                    'country_code' => 'NZ',
                    'month_name' => 'August',
                    'created_by' => 'Craydel',
                    'updated_by' => 'Craydel',
                    'deleted_by' => 'Craydel',
                    'created_at' => '2022-05-26 08:00:00',
                    'update_at' => '2022-05-26 08:00:00',
                    'deleted_at' => null
                ), 41 => array(
                    'id' => 42,
                    'country_name' => 'New Zealand',
                    'country_code' => 'NZ',
                    'month_name' => 'April',
                    'created_by' => 'Craydel',
                    'updated_by' => 'Craydel',
                    'deleted_by' => 'Craydel',
                    'created_at' => '2022-05-26 08:00:00',
                    'update_at' => '2022-05-26 08:00:00',
                    'deleted_at' => null
                ), 42 => array(
                    'id' => 43,
                    'country_name' => 'New Zealand',
                    'country_code' => 'NZ',
                    'month_name' => 'October',
                    'created_by' => 'Craydel',
                    'updated_by' => 'Craydel',
                    'deleted_by' => 'Craydel',
                    'created_at' => '2022-05-26 08:00:00',
                    'update_at' => '2022-05-26 08:00:00',
                    'deleted_at' => null
                ), 43 => array(
                    'id' => 44,
                    'country_name' => 'Zambia',
                    'country_code' => 'ZM',
                    'month_name' => 'September',
                    'created_by' => 'Craydel',
                    'updated_by' => 'Craydel',
                    'deleted_by' => 'Craydel',
                    'created_at' => '2022-05-26 08:00:00',
                    'update_at' => '2022-05-26 08:00:00',
                    'deleted_at' => null
                ), 44 => array(
                    'id' => 45,
                    'country_name' => 'Zambia',
                    'country_code' => 'ZM',
                    'month_name' => 'March',
                    'created_by' => 'Craydel',
                    'updated_by' => 'Craydel',
                    'deleted_by' => 'Craydel',
                    'created_at' => '2022-05-26 08:00:00',
                    'update_at' => '2022-05-26 08:00:00',
                    'deleted_at' => null
                ), 45 => array(
                    'id' => 46,
                    'country_name' => 'Malawi',
                    'country_code' => 'MW',
                    'month_name' => 'January',
                    'created_by' => 'Craydel',
                    'updated_by' => 'Craydel',
                    'deleted_by' => 'Craydel',
                    'created_at' => '2022-05-26 08:00:00',
                    'update_at' => '2022-05-26 08:00:00',
                    'deleted_at' => null
                ), 46 => array(
                    'id' => 47,
                    'country_name' => 'Malawi',
                    'country_code' => 'MW',
                    'month_name' => 'February',
                    'created_by' => 'Craydel',
                    'updated_by' => 'Craydel',
                    'deleted_by' => 'Craydel',
                    'created_at' => '2022-05-26 08:00:00',
                    'update_at' => '2022-05-26 08:00:00',
                    'deleted_at' => null
                ), 47 => array(
                    'id' => 48,
                    'country_name' => 'Malawi',
                    'country_code' => 'MW',
                    'month_name' => 'March',
                    'created_by' => 'Craydel',
                    'updated_by' => 'Craydel',
                    'deleted_by' => 'Craydel',
                    'created_at' => '2022-05-26 08:00:00',
                    'update_at' => '2022-05-26 08:00:00',
                    'deleted_at' => null
                ), 48 => array(
                    'id' => 49,
                    'country_name' => 'Malawi',
                    'country_code' => 'MW',
                    'month_name' => 'April',
                    'created_by' => 'Craydel',
                    'updated_by' => 'Craydel',
                    'deleted_by' => 'Craydel',
                    'created_at' => '2022-05-26 08:00:00',
                    'update_at' => '2022-05-26 08:00:00',
                    'deleted_at' => null
                ), 49 => array(
                    'id' => 50,
                    'country_name' => 'Malawi',
                    'country_code' => 'MW',
                    'month_name' => 'May',
                    'created_by' => 'Craydel',
                    'updated_by' => 'Craydel',
                    'deleted_by' => 'Craydel',
                    'created_at' => '2022-05-26 08:00:00',
                    'update_at' => '2022-05-26 08:00:00',
                    'deleted_at' => null
                ), 50 => array(
                    'id' => 51,
                    'country_name' => 'Malawi',
                    'country_code' => 'MW',
                    'month_name' => 'June',
                    'created_by' => 'Craydel',
                    'updated_by' => 'Craydel',
                    'deleted_by' => 'Craydel',
                    'created_at' => '2022-05-26 08:00:00',
                    'update_at' => '2022-05-26 08:00:00',
                    'deleted_at' => null
                ), 51 => array(
                    'id' => 52,
                    'country_name' => 'Malawi',
                    'country_code' => 'MW',
                    'month_name' => 'July',
                    'created_by' => 'Craydel',
                    'updated_by' => 'Craydel',
                    'deleted_by' => 'Craydel',
                    'created_at' => '2022-05-26 08:00:00',
                    'update_at' => '2022-05-26 08:00:00',
                    'deleted_at' => null
                ), 52 => array(
                    'id' => 53,
                    'country_name' => 'Malawi',
                    'country_code' => 'MW',
                    'month_name' => 'August',
                    'created_by' => 'Craydel',
                    'updated_by' => 'Craydel',
                    'deleted_by' => 'Craydel',
                    'created_at' => '2022-05-26 08:00:00',
                    'update_at' => '2022-05-26 08:00:00',
                    'deleted_at' => null
                ), 53 => array(
                    'id' => 54,
                    'country_name' => 'Malawi',
                    'country_code' => 'MW',
                    'month_name' => 'September',
                    'created_by' => 'Craydel',
                    'updated_by' => 'Craydel',
                    'deleted_by' => 'Craydel',
                    'created_at' => '2022-05-26 08:00:00',
                    'update_at' => '2022-05-26 08:00:00',
                    'deleted_at' => null
                ), 54 => array(
                    'id' => 55,
                    'country_name' => 'Malawi',
                    'country_code' => 'MW',
                    'month_name' => 'October',
                    'created_by' => 'Craydel',
                    'updated_by' => 'Craydel',
                    'deleted_by' => 'Craydel',
                    'created_at' => '2022-05-26 08:00:00',
                    'update_at' => '2022-05-26 08:00:00',
                    'deleted_at' => null
                ), 55 => array(
                    'id' => 56,
                    'country_name' => 'Malawi',
                    'country_code' => 'MW',
                    'month_name' => 'November',
                    'created_by' => 'Craydel',
                    'updated_by' => 'Craydel',
                    'deleted_by' => 'Craydel',
                    'created_at' => '2022-05-26 08:00:00',
                    'update_at' => '2022-05-26 08:00:00',
                    'deleted_at' => null
                ), 56 => array(
                    'id' => 57,
                    'country_name' => 'Malawi',
                    'country_code' => 'MW',
                    'month_name' => 'December',
                    'created_by' => 'Craydel',
                    'updated_by' => 'Craydel',
                    'deleted_by' => 'Craydel',
                    'created_at' => '2022-05-26 08:00:00',
                    'update_at' => '2022-05-26 08:00:00',
                    'deleted_at' => null
                ), 57 => array(
                    'id' => 58,
                    'country_name' => 'South Africa',
                    'country_code' => 'ZM',
                    'month_name' => 'January',
                    'created_by' => 'Craydel',
                    'updated_by' => 'Craydel',
                    'deleted_by' => 'Craydel',
                    'created_at' => '2022-05-26 08:00:00',
                    'update_at' => '2022-05-26 08:00:00',
                    'deleted_at' => null
                ), 58 => array(
                    'id' => 59,
                    'country_name' => 'South Africa',
                    'country_code' => 'ZM',
                    'month_name' => 'February',
                    'created_by' => 'Craydel',
                    'updated_by' => 'Craydel',
                    'deleted_by' => 'Craydel',
                    'created_at' => '2022-05-26 08:00:00',
                    'update_at' => '2022-05-26 08:00:00',
                    'deleted_at' => null
                ), 59 => array(
                    'id' => 60,
                    'country_name' => 'South Africa',
                    'country_code' => 'ZM',
                    'month_name' => 'March',
                    'created_by' => 'Craydel',
                    'updated_by' => 'Craydel',
                    'deleted_by' => 'Craydel',
                    'created_at' => '2022-05-26 08:00:00',
                    'update_at' => '2022-05-26 08:00:00',
                    'deleted_at' => null
                ), 60 => array(
                    'id' => 61,
                    'country_name' => 'South Africa',
                    'country_code' => 'ZM',
                    'month_name' => 'April',
                    'created_by' => 'Craydel',
                    'updated_by' => 'Craydel',
                    'deleted_by' => 'Craydel',
                    'created_at' => '2022-05-26 08:00:00',
                    'update_at' => '2022-05-26 08:00:00',
                    'deleted_at' => null
                ), 61 => array(
                    'id' => 62,
                    'country_name' => 'South Africa',
                    'country_code' => 'ZM',
                    'month_name' => 'May',
                    'created_by' => 'Craydel',
                    'updated_by' => 'Craydel',
                    'deleted_by' => 'Craydel',
                    'created_at' => '2022-05-26 08:00:00',
                    'update_at' => '2022-05-26 08:00:00',
                    'deleted_at' => null
                ), 62 => array(
                    'id' => 63,
                    'country_name' => 'South Africa',
                    'country_code' => 'ZM',
                    'month_name' => 'June',
                    'created_by' => 'Craydel',
                    'updated_by' => 'Craydel',
                    'deleted_by' => 'Craydel',
                    'created_at' => '2022-05-26 08:00:00',
                    'update_at' => '2022-05-26 08:00:00',
                    'deleted_at' => null
                ), 63 => array(
                    'id' => 64,
                    'country_name' => 'South Africa',
                    'country_code' => 'ZM',
                    'month_name' => 'July',
                    'created_by' => 'Craydel',
                    'updated_by' => 'Craydel',
                    'deleted_by' => 'Craydel',
                    'created_at' => '2022-05-26 08:00:00',
                    'update_at' => '2022-05-26 08:00:00',
                    'deleted_at' => null
                ), 64 => array(
                    'id' => 65,
                    'country_name' => 'South Africa',
                    'country_code' => 'ZM',
                    'month_name' => 'August',
                    'created_by' => 'Craydel',
                    'updated_by' => 'Craydel',
                    'deleted_by' => 'Craydel',
                    'created_at' => '2022-05-26 08:00:00',
                    'update_at' => '2022-05-26 08:00:00',
                    'deleted_at' => null
                ), 65 => array(
                    'id' => 66,
                    'country_name' => 'South Africa',
                    'country_code' => 'ZM',
                    'month_name' => 'September',
                    'created_by' => 'Craydel',
                    'updated_by' => 'Craydel',
                    'deleted_by' => 'Craydel',
                    'created_at' => '2022-05-26 08:00:00',
                    'update_at' => '2022-05-26 08:00:00',
                    'deleted_at' => null
                ), 66 => array(
                    'id' => 67,
                    'country_name' => 'South Africa',
                    'country_code' => 'ZM',
                    'month_name' => 'October',
                    'created_by' => 'Craydel',
                    'updated_by' => 'Craydel',
                    'deleted_by' => 'Craydel',
                    'created_at' => '2022-05-26 08:00:00',
                    'update_at' => '2022-05-26 08:00:00',
                    'deleted_at' => null
                ), 67 => array(
                    'id' => 68,
                    'country_name' => 'South Africa',
                    'country_code' => 'ZM',
                    'month_name' => 'November',
                    'created_by' => 'Craydel',
                    'updated_by' => 'Craydel',
                    'deleted_by' => 'Craydel',
                    'created_at' => '2022-05-26 08:00:00',
                    'update_at' => '2022-05-26 08:00:00',
                    'deleted_at' => null
                ), 68 => array(
                    'id' => 69,
                    'country_name' => 'South Africa',
                    'country_code' => 'ZM',
                    'month_name' => 'December',
                    'created_by' => 'Craydel',
                    'updated_by' => 'Craydel',
                    'deleted_by' => 'Craydel',
                    'created_at' => '2022-05-26 08:00:00',
                    'update_at' => '2022-05-26 08:00:00',
                    'deleted_at' => null
                ), 69 => array(
                    'id' => 70,
                    'country_name' => 'Guyana',
                    'country_code' => 'GY',
                    'month_name' => 'September',
                    'created_by' => 'Craydel',
                    'updated_by' => 'Craydel',
                    'deleted_by' => 'Craydel',
                    'created_at' => '2022-05-26 08:00:00',
                    'update_at' => '2022-05-26 08:00:00',
                    'deleted_at' => null
                ), 70 => array(
                    'id' => 71,
                    'country_name' => 'Guyana',
                    'country_code' => 'GY',
                    'month_name' => 'March',
                    'created_by' => 'Craydel',
                    'updated_by' => 'Craydel',
                    'deleted_by' => 'Craydel',
                    'created_at' => '2022-05-26 08:00:00',
                    'update_at' => '2022-05-26 08:00:00',
                    'deleted_at' => null
                )
            ) );
        });
    }
}
